"""Create initial tables

Revision ID: 28257ffb6f6e
Revises: 
Create Date: 2025-03-20 14:23:46.716853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28257ffb6f6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_dim_locations_location_id'), 'dim_locations', ['location_id'], unique=False)
    op.create_table('dim_vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('prod_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('propulsion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_dim_vehicle_vehicle_id'), 'dim_vehicle', ['vehicle_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dim_supplier',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['dim_locations.location_id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_dim_supplier_supplier_id'), 'dim_supplier', ['supplier_id'], unique=False)
    op.create_table('dim_parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('last_id_purchase', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['dim_supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_dim_parts_part_id'), 'dim_parts', ['part_id'], unique=False)
    op.create_table('dim_purchances',
    sa.Column('purchance_id', sa.Integer(), nullable=False),
    sa.Column('purchance_type', sa.String(), nullable=True),
    sa.Column('purchance_date', sa.Date(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['dim_parts.part_id'], ),
    sa.PrimaryKeyConstraint('purchance_id')
    )
    op.create_index(op.f('ix_dim_purchances_purchance_id'), 'dim_purchances', ['purchance_id'], unique=False)
    op.create_table('fact_warranties',
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('claim_key', sa.Integer(), nullable=False),
    sa.Column('repair_date', sa.Date(), nullable=True),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column('tech_comment', sa.Text(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('classifed_as', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('purchance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['dim_locations.location_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['dim_parts.part_id'], ),
    sa.ForeignKeyConstraint(['purchance_id'], ['dim_purchances.purchance_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['dim_vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('claim_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_warranties')
    op.drop_index(op.f('ix_dim_purchances_purchance_id'), table_name='dim_purchances')
    op.drop_table('dim_purchances')
    op.drop_index(op.f('ix_dim_parts_part_id'), table_name='dim_parts')
    op.drop_table('dim_parts')
    op.drop_index(op.f('ix_dim_supplier_supplier_id'), table_name='dim_supplier')
    op.drop_table('dim_supplier')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dim_vehicle_vehicle_id'), table_name='dim_vehicle')
    op.drop_table('dim_vehicle')
    op.drop_index(op.f('ix_dim_locations_location_id'), table_name='dim_locations')
    op.drop_table('dim_locations')
    # ### end Alembic commands ###
